const { PrismaClient } = require("./generated/prisma");
const prisma = new PrismaClient();

async function seedDatabase() {
  const tabeles = [
    ,
    /*"User"*/ "employee",
    "trader",
    "expense",
    "income",
    "transactions",
  ];

  const transaction = [
    {
      id: 6,
      amount: 5700,
      description: "error",
      employeeId: 8,
      traderId: null,
      ExpenseId: null,
      incomeId: null,
      dayId: null,
    },
    {
      id: 7,
      amount: 3,
      description: "aut",
      employeeId: 9,
      traderId: null,
      ExpenseId: null,
      incomeId: null,
      dayId: null,
    },
    {
      id: 8,
      amount: 689384000,
      description: "modi",
      employeeId: 9,
      traderId: null,
      ExpenseId: null,
      incomeId: null,
      dayId: null,
    },
    {
      id: 10,
      amount: 249956,
      description: "natus",
      employeeId: 4,
      traderId: null,
      ExpenseId: null,
      incomeId: null,
      dayId: null,
    },
    {
      id: 6,
      amount: 4395790,
      description: "alias",
      employeeId: null,
      traderId: 2,
      ExpenseId: null,
      incomeId: null,
      dayId: null,
    },
    {
      id: 8,
      amount: 8,
      description: "in",
      employeeId: null,
      traderId: 2,
      ExpenseId: null,
      incomeId: null,
      dayId: null,
    },
    {
      id: 9,
      amount: 3,
      description: "veniam",
      employeeId: null,
      traderId: 1,
      ExpenseId: null,
      incomeId: null,
      dayId: null,
    },
    {
      id: 10,
      amount: 2754090,
      description: "molestias",
      employeeId: null,
      traderId: 6,
      ExpenseId: null,
      incomeId: null,
      dayId: null,
    },
  ];

  const trader = [
    { id: 1, name: "Brielle Klocko", balance: 3 },
    { id: 2, name: "Rose Lang II", balance: 51473200 },
    { id: 3, name: "Janis Wolf", balance: 0 },
    { id: 4, name: "Dr. Suzanne Dach DDS", balance: 690617 },
    { id: 5, name: "Katarina Block", balance: 82820 },
    { id: 6, name: "Dr. Tito Gleason Sr.", balance: 418 },
    { id: 7, name: "Jazmyn Rosenbaum", balance: 4055440 },
    { id: 8, name: "Keely Kilback", balance: 9530 },
    { id: 9, name: "Miss Rosie Kuhlman", balance: 684 },
    { id: 10, name: "Jaylan Runte", balance: 57254 },
    { id: 11, name: "Dr. Nadia Rowe Jr.", balance: 605328 },
    { id: 12, name: "Dr. Colin Blick", balance: 0 },
    { id: 13, name: "Skye Sawayn I", balance: 978662 },
    { id: 14, name: "Cydney McGlynn", balance: 80555200 },
    { id: 15, name: "Carolyne Larkin MD", balance: 6 },
    { id: 16, name: "Mr. Marques Lemke MD", balance: 0 },
    { id: 17, name: "Ethel Corkery", balance: 0 },
    { id: 18, name: "Marcus Romaguera", balance: 1823860 },
    { id: 19, name: "Donato Kuhic", balance: 591286000 },
    { id: 20, name: "Carrie Braun", balance: 38 },
  ];

  const employee = [
    {
      id: 1,
      name: "Sylvan Collier IV",
      dayly: 3,
      weekly: 0,
      monthly: 0,
      balance: 80213000,
    },
    {
      id: 2,
      name: "Ms. Josie Dare II",
      dayly: 8,
      weekly: 0,
      monthly: 0,
      balance: 6,
    },
    {
      id: 3,
      name: "Summer Durgan",
      dayly: 4,
      weekly: 0,
      monthly: 0,
      balance: 722205,
    },
    {
      id: 4,
      name: "Edd Fisher II",
      dayly: 5,
      weekly: 0,
      monthly: 0,
      balance: 938,
    },
    {
      id: 5,
      name: "Leonel Halvorson",
      dayly: 2,
      weekly: 0,
      monthly: 0,
      balance: 47907,
    },
    {
      id: 6,
      name: "Earline Gutkowski Sr.",
      dayly: 9,
      weekly: 0,
      monthly: 0,
      balance: 432,
    },
    {
      id: 7,
      name: "Prof. Otto Sawayn PhD",
      dayly: 1,
      weekly: 0,
      monthly: 0,
      balance: 12370,
    },
    {
      id: 8,
      name: "Ms. Abbigail Rau",
      dayly: 7,
      weekly: 0,
      monthly: 0,
      balance: 0,
    },
    {
      id: 9,
      name: "Prof. Audreanne Lehner",
      dayly: 4,
      weekly: 0,
      monthly: 0,
      balance: 5,
    },
    {
      id: 10,
      name: "Shirley Price",
      dayly: 4,
      weekly: 0,
      monthly: 0,
      balance: 29633500,
    },
    {
      id: 11,
      name: "Cassidy Bins",
      dayly: 7,
      weekly: 0,
      monthly: 0,
      balance: 153100,
    },
    {
      id: 12,
      name: "Lyla Erdman",
      dayly: 5,
      weekly: 0,
      monthly: 0,
      balance: 654,
    },
    {
      id: 13,
      name: "Niko Rosenbaum",
      dayly: 8,
      weekly: 0,
      monthly: 0,
      balance: 7,
    },
    {
      id: 14,
      name: "Mrs. Simone Jacobs DVM",
      dayly: 1,
      weekly: 0,
      monthly: 0,
      balance: 705663000,
    },
    {
      id: 15,
      name: "Precious Kunde",
      dayly: 9,
      weekly: 0,
      monthly: 0,
      balance: 5033970,
    },
    {
      id: 16,
      name: "Dr. Elton Gleichner",
      dayly: 6,
      weekly: 0,
      monthly: 0,
      balance: 26,
    },
    {
      id: 17,
      name: "Alicia Kerluke Jr.",
      dayly: 7,
      weekly: 0,
      monthly: 0,
      balance: 95,
    },
    {
      id: 18,
      name: "Clinton Kuhlman Sr.",
      dayly: 1,
      weekly: 0,
      monthly: 0,
      balance: 1,
    },
    {
      id: 19,
      name: "Prof. Louie Dicki",
      dayly: 8,
      weekly: 0,
      monthly: 0,
      balance: 72267300,
    },
    {
      id: 20,
      name: "Destini Hettinger IV",
      dayly: 8,
      weekly: 0,
      monthly: 0,
      balance: 62,
    },
  ];

  for (i in tabeles) {
    console.log(tabeles[i]);
  }
}

seedDatabase();
